POST http://localhost:8080/api/bowls/
Content-Type: application/json
Cache-Control: no-cache

{
  "name": "Boisy's Bowl"
}

####

PUT http://localhost:8080/api/bowls/c2f81a47-63b2-4133-93e6-b8ab57f3c423
Content-Type: application/json
Cache-Control: no-cache

{
  "waterlevel": 80
}

####

GET http://localhost:8080/api/bowls/c2f81a47-63b2-4133-93e6-b8ab57f3c423
Content-Type: application/json
Cache-Control: no-cache