version: '3.7'

services: 
  smart-dog-api:
    build: 
      context: smartDog-api/
      dockerfile: Dockerfile
    ports: 
      - 8080:8080
    networks: 
      - backend

networks: 
  frondend:
  backend:

volumes: 
  db-data: